"""
Django settings for config_manager project.

Generated by 'django-admin startproject' using Django 5.2.
"""
from pathlib import Path
import os
import environ

from typing import List, Dict, Tuple, Any, Union


BASE_DIR: Path = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    POSTGRES_HOST=str,
    POSTGRES_PORT=int,
    POSTGRES_DB=str,
    POSTGRES_USER=str,
    POSTGRES_PASSWORD=str,
    DJANGO_ALLOWED_HOSTS=list,
    SECRET_KEY=str,
)

env_dir = os.path.join(BASE_DIR, '.env')
environ.Env.read_env(env_dir)


SECRET_KEY: str = env('SECRET_KEY')
DEBUG: bool = env.bool('DEBUG', default=False)
ALLOWED_HOSTS: List[str] = env.list('DJANGO_ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS: List[str] = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'config_app',
    'constance',
]

MIDDLEWARE: List[str] = [
    'config_app.middleware.LogRequestPIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF: str = 'config_manager.urls'

TEMPLATES: List[Dict[str, Any]] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION: str = 'config_manager.wsgi.application'


# Database

DATABASES: Dict[str, Dict[str, Any]] = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env.int('POSTGRES_PORT'),
    }
}


# Constance settings - - - define realtime configs here!

CONSTANCE_BACKEND: str = 'constance.backends.redisd.RedisBackend'

CONSTANCE_REDIS_CONNECTION: Dict[str, Union[str, int]] = {
    'host': env('REDIS_HOST'),
    'port': env.int('REDIS_PORT'),
    'db': env.int('REDIS_DB'),
}

CONSTANCE_CONFIG: Dict[str, Tuple[Any, str, type]] = {
    # 'CONFIG_NAME': (default, 'description', config type)
    'SITE_NAME': ('Config Manager', 'Site name', str),
    'WELCOME_MESSAGE': ('You can see real-time configs and their values here', 'Welcome text', str),
    'THEME_COLOR': ('#4a6cf7', 'Background theme colour in HEX', str),
    'MAINTENANCE_MODE': (False, 'Maintenance mode', bool),
    'ITEMS_PER_PAGE': (5, 'Config items per page', int),

    'SHOW_LOGS': (True, 'Show change logs', bool),
    'LOGS_COUNT': (10, 'Number of recent change logs to show', int),

    'UI_POLLING_INTERVAL': (300.0, 'Polling interval for real-time UI, s', float),
}

# Any config you add must appear here in some fieldset! also definable
CONSTANCE_CONFIG_FIELDSETS: Dict[str, Tuple[str, ...]] = {
    'General': ('SITE_NAME', 'THEME_COLOR', 'MAINTENANCE_MODE'),
    'Content': ('WELCOME_MESSAGE', 'ITEMS_PER_PAGE'),
    'Logging': ('SHOW_LOGS', 'LOGS_COUNT'),
    'Demo': ('UI_POLLING_INTERVAL',)
}

REDIS_PUB_SUB_CHANNEL: str = 'realtime_config_updates'

# Time to wait for before trying to connect to Redis again
REDIS_RETRY_INTERVAL: float = 10.0


# Logging

LOGGING: Dict[str, Any] = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'config_app': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Password validation

AUTH_PASSWORD_VALIDATORS: List[Dict[str, str]] = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE: str = 'en-us'
TIME_ZONE: str = 'UTC'
USE_I18N: bool = True
USE_TZ: bool = True

# Static files (CSS, JavaScript, Images)

STATIC_URL: str = 'static/'

# Default primary key field type

DEFAULT_AUTO_FIELD: str = 'django.db.models.BigAutoField'
